---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-centos-8
metadata: 
  name: agent-integration-tests
  description: "Cluster for Agent Integration Tests (AWS EC2 / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  region: eu-central-1
  wireguard: false
  versions:
    stackable-agent: "*0.nightly.el8.x86_64"
  nodes:
    main:
      numberOfNodes: 1
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
    testdriver:
      numberOfNodes: 1
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
      agent: false
