---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: ionos-centos-7
metadata: 
  name: agent-integration-tests
  description: "Cluster for Agent Integration Tests (IONOS / CentOS 7)"
domain: stackable.test
publicKeys: []
spec:
  region: de/fra
  wireguard: false
  versions:
    stackable-agent: "$AGENT_VERSION"
  nodes:
    main:
      numberOfNodes: 1
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
    testdriver:
      numberOfNodes: 1
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
      agent: false
